{
 "title": "Rocket.Chat Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(kube_deployment_metadata_generation{namespace=\"$deployment_namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Users Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_online{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users Away",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_away{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "DDP Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Rooms  Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Messages  Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Handles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total{DeploymentName=\"open\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_requests_total{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event loop lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (space) (nodejs_heap_size_used_bytes{DeploymentName=\"$deployment\"})",
       "legendFormat": "{{space}}"
      }
     ]
    },
    {
     "title": "Per pod heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}} [{{space}}]"
      }
     ]
    }
   ]
  },
  { "title": "RocketChat Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Messages Sent (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_message_sent{DeploymentName=\"$deployment\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Users & Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"})",
     "legendFormat": "Connected Users"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_count{DeploymentName=\"$deployment\"})",
     "legendFormat": "All Sessions"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_auth{DeploymentName=\"$deployment\"})",
     "legendFormat": "Authenticated Sessions "
    }
   ]
  },
  {
   "title": "Meteor Methods Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_methods{DeploymentName=\"$deployment\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Meteor Methods Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_methods_count{DeploymentName=\"$deployment\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Meteor Subscription Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_subscriptions{DeploymentName=\"$deployment\"}) by (subscription)",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Meteor Subscription Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_subscriptions_count{DeploymentName=\"$deployment\"}[1m])) by (subscription)",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Total of Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Total of Rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})",
     "legendFormat": "Rooms"
    }
   ]
  },
  {
   "title": "Callbacks Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_callbacks{DeploymentName=\"$deployment\"}) by (callback)",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "Callbacks Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_callbacks_count{DeploymentName=\"$deployment\"}[1m])) by (callback)",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "Hooks Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_hooks{DeploymentName=\"$deployment\"}) by (hook)",
     "legendFormat": "{{hook}}"
    }
   ]
  },
  {
   "title": "Hooks Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_hooks_count{DeploymentName=\"$deployment\"}[1m])) by (hook)",
     "legendFormat": "{{hook}}"
    }
   ]
  },
  {
   "title": "REST API Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_rest_api{DeploymentName=\"$deployment\"}) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "REST API Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_rest_api_count{DeploymentName=\"$deployment\"}[1m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_notification_sent{DeploymentName=\"$deployment\"}) by (notification_type)",
     "legendFormat": "{{notification_type}}"
    }
   ]
  }
 ]
}